### ISSUE TITLE
[Feature/featureName] 버튼 색상 변경

### ISSUE THREAD

**Issue by nayeon0891** [1teamPJ/Mohaeng#12]
## 🛠️ 기능 설명
> 게시글 작성 버튼 색상 변경했습니다.

## 📝 작업 진행 체크리스트

- [ ] MVC 모델 준수
- [ ] 콘솔 출력
- [ ] 최종 구현

## 📚 참고 자료(선택사항)
>

## ✅ 테스트 결과(이미지)(선택사항)
>
![image](https://github.com/1teamPJ/Mohaeng/assets/132421122/77f89651-225a-4de1-8cb4-dbd2716991e3)

**Comment by hyojunahn111** [comment]
확인했습니다.
