### ISSUE TITLE
[Mohaeng/CBboard] CBborad 기능구현

### ISSUE THREAD

**Issue by Realyunjae** [1teamPJ/Mohaeng#13]
## 🛠️ 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택사항)
>

## ✅ 테스트 결과(이미지)(선택사항)

>
<img width="1440" alt="스크린샷 2024-05-03 오후 3 21 40" src="https://github.com/1teamPJ/Mohaeng/assets/129252557/b5137b6c-f29c-49b0-bb44-e5fa6666d7f9">

**Comment by hyojunahn111** [comment]
확인했습니다.
