### ISSUE TITLE
[Feature/featureName] css 디자인 수정

### ISSUE THREAD

**Issue by a75372656** [1teamPJ/Mohaeng#14]
## 🛠️ 기능 설명
> css 디자인 수정
## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택사항)
>

## ✅ 테스트 결과(이미지)(선택사항)
>
![image](https://github.com/1teamPJ/Mohaeng/assets/162537542/8ed7f7f3-c0fb-4c1e-a956-cafa7ad1e89f)

**Comment by hyojunahn111** [comment]
확인했습니다.
