### ISSUE TITLE
[mohaeng/main] Navvar 구성 및 파일 모델링

### ISSUE THREAD

**Issue by ohdyo** [1teamPJ/Mohaeng#15]
## 🛠️ 기능 설명
> Navvar 및 파일 모델링 했습니다.

## 📝 작업 진행 체크리스트

- [ v] 모델링
- [ v] Navvar 파일 작성

## 특이사항
일단 브랜치의 이름을 따라서 만들었으니까 다 수정해야하면 경로랑 이름 바꿔주세요

**Comment by hyojunahn111** [comment]
확인했습니다.
