### ISSUE TITLE
[Mohaeng/CBborad] CBborad main과 페이지 연결 

### ISSUE THREAD

**Issue by Realyunjae** [1teamPJ/Mohaeng#19]
## 🛠️ 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택사항)
>
CbLayout.js 생성
checkboard 삭제
## ✅ 테스트 결과(이미지)(선택사항)
>

**Comment by hyojunahn111** [comment]
확인했습니다.
