### ISSUE TITLE
[Feature/featureName] 풋터 구현 완료

### ISSUE THREAD

**Issue by nayeon0891** [1teamPJ/Mohaeng#25]
## 🛠️ 기능 설명
> 풋터 구현 했습니다

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택사항)
>

## ✅ 테스트 결과(이미지)(선택사항)
>
![image](https://github.com/1teamPJ/Mohaeng/assets/132421122/8b5880db-85b8-47d4-bcb3-4c544ec0e362)

**Comment by hyojunahn111** [comment]
확인했습니다.
