### ISSUE TITLE
[Mohaeng/main] 지역 한글이름으로 번역

### ISSUE THREAD

**Issue by ohdyo** [1teamPJ/Mohaeng#4]
## 🛠️ 기능 설명
> 지도에서 선택한 지역에 맞게 한글로 번역하게 구현

## 📝 작업 진행 체크리스트

- [ v ] 콘솔 출력

## 특이사항
- select태그의 option태그 안에도 이너텍스트를 변경하고 싶지만 그러면 state가 변경할때마다 다 같이 변해서 좀더 봐야할 필요가 있습니다.

**Comment by hyojunahn111** [comment]
확인했습니다.
