### ISSUE TITLE
[Mohaeng/Checkboard] 한글 오타 수정

### ISSUE THREAD

**Issue by Realyunjae** [1teamPJ/Mohaeng#42]
## 🛠️ 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택사항)
>

## ✅ 테스트 결과(이미지)(선택사항)
>
<img width="899" alt="스크린샷 2024-05-05 오후 8 08 42" src="https://github.com/1teamPJ/Mohaeng/assets/129252557/362a5b2c-513a-46f7-b2bb-65f1ed0f94c4">

**Comment by hyojunahn111** [comment]
확인했습니다.
