### ISSUE TITLE
[Mohaeng/main] 게시글 예시 작성

### ISSUE THREAD

**Issue by ohdyo** [1teamPJ/Mohaeng#6]
## 🛠️ 기능 설명
> 각 지역별 게시글이 보이게 예시 작성

## 📝 작업 진행 체크리스트

- [ v] 콘솔 출력

## 특이사항
> 각 지역별로 리스트 스테이트를 담아두고 계속 변경시켜서 만들 예정 일단 보여주기 식으로 하나 작성 했습니다.

**Comment by hyojunahn111** [comment]
확인했습니다.
