### ISSUE TITLE
[Feature/featureName] 이미지 업로드 수정

### ISSUE THREAD

**Issue by nayeon0891** [1teamPJ/Mohaeng#9]
## 🛠️ 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요
이미 등록시 300x300 이미지 출력을 지우고 강제 이미지 업로드 구현
## 📝 작업 진행 체크리스트

- [ ] MVC 모델 준수
- [ ] 콘솔 출력
- [ ] 최종 구현

## 📚 참고 자료(선택사항)
> 

## ✅ 테스트 결과(이미지)(선택사항)
>
![image](https://github.com/1teamPJ/Mohaeng/assets/132421122/5c5ed929-b9a2-4e32-9162-fe62f2525252)
이미지 강제 업로드

**Comment by hyojunahn111** [comment]
확인했습니다.
